name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nixbuild/nix-quick-install-action@v34
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}
    - run: nix-build
    - run: ./.github/workflows/update_pages.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TARGET_REPO: ${{ github.repository }}
        RUN_NUMBER: ${{ github.run_number }}
        WORKFLOW: ${{ github.workflow }}
