name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          extra-substituters = file://${{ github.workspace }}/nix-store-cache?trusted=true
    - name: display nix.conf
      run: cat /etc/nix/nix.conf
    - name: echo working directory
      run: echo $PWD
    - uses: cachix/cachix-action@v10
      with:
        name: vaibhavsagar
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Delete existing Nix Store Cache
      run: sudo rm -rf $PWD/nix-store-cache || true
    - name: Setup Nix Cache
      uses: actions/cache@v2
      with:
        path: nix-store-cache
        key: nix-store-cache-${{ github.sha }}
        restore-keys: |
          nix-store-cache-
    - run: nix-build -vv --substituters "file://$PWD/nix-store-cache"
    - name: Rebuild Nix Store Cache
      run: |
        sudo rm -rf $PWD/nix-store-cache || true
        nix copy ./result --to file://$PWD/nix-store-cache?compression=none
    - if: ${{ github.ref == 'refs/heads/master' }}
      run: ./.github/workflows/update_pages.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TARGET_REPO: ${{ github.repository }}
        RUN_NUMBER: ${{ github.run_number }}
        WORKFLOW: ${{ github.workflow }}
